config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ingredients, only: [:index]
  resources :recettes, only: [:index]
  resources :menus, only: [:new, :create]
  get "/ta_liste", to: "menus#liste"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :liste_ingredients
end

app/models/liste_ingredient.rb
class ListeIngredient < ApplicationRecord
  belongs_to :recette
  belongs_to :ingredient
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :recette
end

app/models/recette.rb
class Recette < ApplicationRecord
  has_many :liste_ingredients
  has_many :ingredients, through: :liste_ingredients
  has_many :menus
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [ :default_url_options ]

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new, :liste ]
  def new
    @semaines = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"]
    @recettes = Recette.all.map {|recette| recette.name}
  end
  def liste
    @recettes = params.values.first(7)
    @liste = {}
    @recettes.each do |recette|
      unless recette == ""
        Recette.where(name: recette).first.liste_ingredients.each do |liste_ingredient|
          if @liste[liste_ingredient.ingredient.name].nil?
            @liste[liste_ingredient.ingredient.name] = [liste_ingredient.quantity, liste_ingredient.unit, liste_ingredient.ingredient.rayon]
          else
            @liste[liste_ingredient.ingredient.name][0] += liste_ingredient.quantity
          end
        end
      end
    end
    rayons = @liste.values.map {|a| a[2]}
    rayons = rayons.uniq
    rayons = rayons.sort
    @a_listes = {}
    rayons.each do |rayon|
      @a_listes[rayon] = []
    end
    @liste.each do |key, value|
      @a_listes[value[2]] << {ingredient: key, quantite: value[0], unite: value[1]}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/recettes_controller.rb
class RecettesController < ApplicationController
  def index
    @recettes = Recette.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/ingredients/index.html.erb
<h1>Liste des ingrédients</h1>
<ul>
  <% @ingredients.each do |ingredient| %>
    <li><%= ingredient.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# Favicon %>
    <%= favicon_link_tag %>
    
    <%# meta %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="body">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/menus/liste.html.erb
<h1 class="text-center mt-4">Voici ta liste de course</h1>
<p class="text-center">Bon appétit</p>
<hr>
<div class="cards">
  <% @a_listes.each do |key, value| %>
    <div class="card-category">
      <div class="row justify-content-center">
        <div class="col-10 justify-content-center">
          <h2><%= key %></h2>
          <hr>
          <% value.each do |hash|%>
            <div class="row justify-content-center">
              <div class="col-7">
                <%= hash[:ingredient] %>
              </div>
              <div class="col-3">
                <%= hash[:quantite] %>
              </div>
              <div class="col-2">
                <%= hash[:unite] %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/menus/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 class="text-center mt-3">Que vas tu manger cette semaine ?</h1>
  </div>
  <div class="row justify-content-center">
    <p>Choisis des recettes et obtiens ta liste de course.</p>
  </div>
  <hr>
  <div class="form-group mt-4">
    <%= form_with url: "/ta_liste", method: :get, class: "form-group" do |form| %>
      <% @semaines.each do |repas| %>
        <div class="row justify-content-center">
          <div class="col-6 col-md-3">
            <%= form.label repas.to_s, repas.to_s, class: "form-control" %>
          </div>
          <div class="col-6 col-md-5">
            <%= form.select "recette du #{repas}", @recettes, 
              { selected: "", prompt: 'Ton plat ?' }, 
              class: "form-control" %>
          </div>
        </div>
      <% end %>
      <div class="row justify-content-center mt-4">
        <div class="col-8">
          <h3><%= form.submit "Crée ta liste de course", class: "btn btn-flat form-cntrol w-100" %></h3>
        </div>
      </div>
    <% end %>
  </div>
</div>
  

app/views/pages/home.html.erb
<div class="home-banner">
  <div class="banner-content">
    <h1 class="text-center">Du menu à l'assiette</h1>
    <hr>
    <h3 class="text-center">Façonne ton menu de la semaine</h3>
    <h3 class="text-center">Obtiens ta liste de course</h3>
    <hr>
    <div class="text-center mt-4">
      <%= link_to "Crée ta liste", new_menu_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>
<div class="container mt-4 text-justify">
  <p>Bienvenue sur "Du menu à l'assiette".</p>
  <p>Cette application web a pour but de simplifier ta liste de course. 
  Choisis simplement ce que tu souhaites manger et l'application te génère la liste de 
  course appropriée et triée par rayons.</p>
</div>

app/views/recettes/index.html.erb
<h1>Liste des recettes</h1>
<ul>
  <% @recettes.each do |recette| %>
    <li><%= recette.name %></li>
  <% end %>
</ul>
<%= link_to "Gerer mes ingredients", ingredients_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<hr>
<div class="footer">
  <div class="footer-flex">
    <div class="footer-links">
      <a href="https://github.com/GN13008/ma_liste_de_course"><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/guillaumenegro/"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Design and Concept by  <a href="https://github.com/GN13008"><i class="far fa-copyright"></i> GN Development</i></a>
    </div>
  </div>
  <hr>
  <div>
    <div class="footer mt-2">
      <div class="footer-project">
        <p>"Du Menu à l'Assiette" est ma première application Post formation <a href="https://www.lewagon.com/fr">LeWagon</a>. 
        L'objectif principal étant de continuer à apprendre en développant mes idées.</p>
        <p>Elle est au stade de MVP. Plus de détails (axes d'améliorations, remarques, ...) sur le readme : <a href="https://github.com/GN13008/ma_liste_de_course">ici</a></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_mldc.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Mes recettes",recettes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <%# code in case I want a profil management %>
        <%# <li class="nav-item dropdown"> %>
          <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <%# <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown"> %>
            <%# <%= link_to "Action", "#", class: "dropdown-item" %>
            <%# <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%# <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <%# </div> %>
        <%# </li> %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>